#!/usr/bin/env bash
echo ""
echo "Starting Server Script..."
echo ""
echo "Running npm install..."
echo ""
docker run -ti --rm -v "$(pwd):/myapp" -w '/myapp' 'node:6.9.1' npm install
echo "-----------------------"
# echo ""
# echo "Running scss-lint..."
# echo ""
# docker run -ti --rm -v "$(pwd):/myapp" -w '/myapp' -p 4000:4000 'webstop/jekyll:latest' bundle exec scss-lint --config .scss-lint.yml scss/*.scss
# echo "-----------------------"
echo ""
echo "Running npm run dist..."
echo ""
docker run -ti --rm -v "$(pwd):/myapp" -w '/myapp' 'node:6.9.1' npm run dist
echo "-----------------------"
echo ""
echo "Running jekyll serve..."
echo ""
docker run -ti --rm -v "$(pwd):/myapp" -p 4000:4000 'webstop/jekyll:latest' jekyll serve --incremental
