#!/usr/bin/env bash

docker run -ti --rm -v "$(pwd):/myapp" -w '/myapp' 'node:11' npm install
# docker run -ti --rm -v "$(pwd):/myapp" -w '/myapp' 'node:11' yarn install --modules-folder vendor/assets/node_modules

docker-compose run jekyll bundle update
