#!/usr/bin/env bash

docker run -ti --rm -v "$(pwd):/myapp" -w '/myapp' 'node:16.13' npm install

docker run -ti --rm -v "$(pwd):/myapp" -w '/myapp' 'node:16.13' npm update

docker-compose run jekyll bundle update
