#!/usr/bin/env bash
echo ""
echo "Starting Sass Watch Script..."
echo ""
echo "Running npm install..."
echo ""
docker run -ti --rm -v "$(pwd):/myapp" -w '/myapp' 'node:8' yarn install
echo "--------------------"
# echo ""
# echo "Running scss-lint..."
# echo ""
# docker run -ti --rm -v "$(pwd):/myapp" -w '/myapp' -p 4000:4000 'webstop/jekyll:latest' bundle exec scss-lint --config .scss-lint.yml scss/*.scss
# echo "-----------------------"
echo ""
echo "Running npm run dist..."
echo ""
docker run -ti --rm -v "$(pwd):/myapp" -w '/myapp' 'node:8' npm run dist
echo "------------------------"
echo ""
echo "Running npm run watch..."
echo ""
docker run -ti --rm -v "$(pwd):/myapp" -w '/myapp' 'node:8' npm run watch
